<?php require_once 'header.phtml'; ?>

<h2>Editar producto</h2>

<form action="<?= BASE_URL ?>updateProduct" method="post">

    <input type="hidden" name="id_producto" value="<?= $product->id_producto ?>">

    <label>Nombre del producto:</label>
    <input type="text" name="nombre_producto" value="<?= $product->nombre_producto ?>" required>

    <label>Descripción:</label>
    <input type="text" name="descripcion_producto" value="<?= $product->descripcion_producto ?>" required>

    <label>Precio:</label>
    <input type="number" step="0.01" name="precio_producto" value="<?= $product->precio_producto ?>" required>

    <label for="">Categoría</label>
    <select name="fk_id_categoria" required>
        <option value="">Seleccione una categoría</option>
        <?php foreach ($category as $c): ?>
            <option value="<?= $c->id_categoria ?>"><?= $c->nombre_categoria ?></option>
        <?php endforeach ?>
    </select>

    <button type="submit" class="btn btn-primary">Actualizar</button>
</form>

<?php require_once 'footer.phtml'; ?>