<?php require_once 'header.phtml' ?>

<p>En Tudai, siempre hay algo para vos. Somos un comercio de barrio con alma de gran almacén: variedad, buenos precios y atención cercana. Desde artículos para el hogar, productos de limpieza, herramientas, hasta esos detalles que necesitás en el día a día… todo lo encontrás acá.

  ¿Buscás algo puntual? ¿Necesitás resolver rápido? Pasá por Tudai y seguro lo tenés. Renovamos nuestro stock constantemente para ofrecerte opciones prácticas, útiles y accesibles.

  ¿Qué encontrás en Tudai?

  Artículos de ferretería

  Productos de limpieza

  Electrodomésticos y pequeños electrónicos

  Bazar, cocina y hogar

  Juguetes y artículos de temporada

  ¡Y mucho más!

  Somos ese lugar al que venís por una cosa y te vas con tres (¡porque todo te sirve!). Porque en Tudai, lo importante no es sólo lo que buscás, sino todo lo que podés encontrar.</p>
<?php require_once 'footer.phtml' ?>