<?php require_once 'header.phtml'; ?>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Imagen</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($category as $c): ?>
      <tr>
        <td><?= $c->id_categoria ?></td>
        <td><?= $c->nombre_categoria ?></td>
        <td><?= $c->descripcion_categoria ?></td>
        <td>
          <?php if (!empty($c->imagen_categoria)): ?>
            <img src="<?= $c->imagen_categoria ?>" alt="Imagen" width="80">
          <?php else: ?>
            Sin imagen
          <?php endif; ?>
        </td>
        <td><a href="showProductsByCatgory">Ver mas</a></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
<?php require_once './templates/footer.phtml' ?>