<?php require_once 'header.phtml'; ?>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Imagen</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($category as $c): ?>
      <tr>
        <td><?= $c->id_categoria ?></td>
        <td><?= $c->nombre_categoria ?></td>
        <td><?= $c->descripcion_categoria ?></td>
        <td>
          <?php if (!empty($c->imagen_categoria)): ?>
            <img src="<?= $c->imagen_categoria ?>" alt="Imagen" width="80">
          <?php else: ?>
            Sin imagen
          <?php endif; ?>
        </td>
        <td><a href="editCategory/<?= $c->id_categoria ?>" class="btn btn-secondary">Editar</a></td>
        <td><a href="deleteCategory/<?= $c->id_categoria ?>" class="btn btn-danger">Eliminar</a></td>
        <td><a href="<?= BASE_URL ?>showProductsByCategory/<?= $c->id_categoria ?>" class="btn btn-primary">Ver más</a></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<h3>Agregar categoría</h3>
<?php require_once './helper/AuthHelper.php' ?>
<form action="insertCategory" method="post">
  <label>Nombre</label>
  <input type="text" name="nombre_categoria" required>
  <label>Descripción</label>
  <input type="text" name="descripcion_categoria" required>
  <label>URL Imagen</label>
  <input type="url" name="imagen_categoria">
  <button type="submit">Agregar</button>
</form>

<?php require_once 'footer.phtml'; ?>