<form action="register" method="post">
    <label for="">Email</label><input type="text" name="email" id="">
    <label for="">Password</label><input type="password" name="password" id="">
    <input type="submit" value="Registrar">
</form>

<?php if (!empty($error)): ?>
    <div class="alert alert-danger mt-3"><?= $error ?></div>
<?php endif; ?>

<p>Ya tenes cuenta? Logueate <a href="login">aca</a></p>