
<form action="login" method="post">
    <label for="">Email</label><input type="text" name="email" id="">
    <label for="">Password</label><input type="password" name="password" id="">
    <input type="submit" value="Entrar">
</form>
<?php if (!empty($error)): ?>
    <div class="alert alert-danger"><?= $error ?></div>
<?php endif; ?>
<p>No tenes cuenta todavia clic <a href="register">aca</a></p>