<form action="login" method="post">
    <label for="">Email</label><input type="text" name="email">
    <label for="">Password</label><input type="password" name="password">
    <input type="submit" value="Entrar">
</form>

<?php if (!empty($error)): ?>
    <div class="alert alert-danger"><?= $error ?></div>
<?php endif; ?>

<p>No tenés cuenta todavía? Registrate <a href="register">acá</a></p>

<a class="nav-link" href="<?= BASE_URL ?>guest">Entrar como invitado</a>
